name: CI Build

on:
  push:
    branches: [ main ]

  pull_request:
     branches: [ main ]

jobs:
  build:
    continue-on-error: true

    strategy:
      matrix:
        ruby: ['3.1', '3.4', jruby-head]
        operating-system: [ubuntu-latest]
        include:
          - ruby: '3.1'
            operating-system: windows-latest
          - ruby: jruby-head
            operating-system: windows-latest

    name: Ruby ${{ matrix.ruby }} on ${{ matrix.operating-system }}
    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialize Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run rake
        run: bundle exec rake
